// <auto-generated />
using System;
using MarriageRegistryAPI.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MarriageRegistryAPI.Persistence.Migrations
{
    [DbContext(typeof(MarriageRegistryContext))]
    partial class MarriageRegistryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.14")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MarriageRegistryAPI.Persistence.Entities.Marriage", b =>
                {
                    b.Property<int>("MarriageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("MarriageDate")
                        .HasColumnType("datetime2");

                    b.HasKey("MarriageId");

                    b.ToTable("Marriages");
                });

            modelBuilder.Entity("MarriageRegistryAPI.Persistence.Entities.Person", b =>
                {
                    b.Property<int>("PersonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("MarriageId")
                        .HasColumnType("int");

                    b.Property<string>("PersonalCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("PersonId");

                    b.HasIndex("MarriageId");

                    b.ToTable("Persons");
                });

            modelBuilder.Entity("MarriageRegistryAPI.Persistence.Entities.Person", b =>
                {
                    b.HasOne("MarriageRegistryAPI.Persistence.Entities.Marriage", "Marriage")
                        .WithMany("Spouses")
                        .HasForeignKey("MarriageId");

                    b.Navigation("Marriage");
                });

            modelBuilder.Entity("MarriageRegistryAPI.Persistence.Entities.Marriage", b =>
                {
                    b.Navigation("Spouses");
                });
#pragma warning restore 612, 618
        }
    }
}
